version: '3'
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/producer.rb
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/worker.rb
    deploy:
      mode: replicated
      replicas: 10
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
